output: lib/bindings.dart
headers:
  entry-points:
    - native/dr_libphonenumber/target/bindings.h
name: DrLibphonenumberBindings
llvm-path:
  - '/opt/homebrew/Cellar/llvm/12.0.1'
description: Dart bindings to call DrLibphonenumber functions
