output: lib/src/bindings.dart
headers:
  entry-points:
    - native/dr_libphonenumber/target/bindings.h
name: DrLibphonenumberBindings
llvm-path:
  - '/usr/local/homebrew/opt/llvm'
description: Dart bindings to call DrLibphonenumber functions
