name: dr_libphonenumber_platform_interface
description: dr_libphonenumber Platform Interface.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0
