name: dr_libphonenumber_web
description: A simple command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  dr_libphonenumber_platform_interface:
    git:
      url: https://github.com/TabooSun/dr_libphonenumber.git
      ref: v1.0.0-dr_libphonenumber_platform_interface
      path: dr_libphonenumber_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  taboosun_lints:
    git:
      url: https://github.com/TabooSun/dart_taboosun_lints.git
      ref: v1.1.3

flutter:
  plugin:
    platforms:
      web:
        pluginClass: DrLibphonenumberWeb
        fileName: dr_libphonenumber_web.dart
