name: Publish binaries

on:
  create:
    ref_type: tag
    
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make binaries
        run: |
          cd native/dr_libphonenumber
          make init
          make all
      
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "targets"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Cleanup
        run: make clean